### PR TITLE
Refactor src

### PR DESCRIPTION
**Pull request by mjr-deltares**
A first working version of bmi (exposing c-style pointer to our internal arrays). We still need to discuss how we can use the CSDMS interface explicitly, and how they have wrapped it into Python.

### CODE REVIEW

**Comment by mjr-deltares** [comment]
apparently the floating point model on Travis is not equal to the one on my Windows machine, nor to the one I have on my Linux virtual box. Currently I tried making the implementation safe by explicitly assigning `totalsimtime` to `totim` when the simulation is finished.

**Comment by langevin-usgs** [comment]
Working on Travis is like feeling around in the dark...

**Comment by mjr-deltares** [comment]
Yes, it is :-) 

The floating point issue is solved I guess, but would you have an idea why that last test (testmnw2) is still failing?

**Comment by mjr-deltares** [comment]
O, wait, it is quite recent, let me pull develop in first...

**Pull request merged**
