### PR TITLE
ci(parallel): add parallel windows distribution

### PR DESCRIPTION
**Pull request by wpbonelli**
Add a parallel Windows distribution to `release.yml`, making it available both on the nightly build and in official releases. The distribution archive is named `win64par.zip` and contains all non-system dependencies, to avoid the need for software installs or actions requiring elevation for the end user. 

Bundled dependencies include: 
  * MSVC runtime
    * ucrtbase.dll
    * msvcrt.dll
    * msvcp_win.dll
    * MSVCP140.dll
    * VCRUNTIME140.dll
    * VCRUNTIME140_1.dll
  * oneAPI (Fortran compiler, MKL, MPI)
    * libifcoremd.dll
    * libmmd.dll
    * mkl_mc3.2.dll
    * mkl_core.2.dll
    * mkl_avx512.2.dll
    * mkl_avx2.2.dll
    * mkl_def.2.dll
    * mkl_sequential.2.dll
    * libfabric.dll
    * impi.dll
    * mpiexec.exe
    * hydra_bstrap_proxy.exe
    * hydra_pmi_proxy.exe
    * hydra_service.exe
  * PETSc
    * libpetsc.dll

Miscellaneous:
* factor out action to build mf6 parallel on windows
* add `developmode` toggle to `release_dispatch.yml`

### CODE REVIEW

**Comment by wpbonelli** [comment]
There is a test build available here: https://github.com/wpbonelli/modflow6/actions/runs/8361786337

This should be ready to go. @rbwinst-usgs has confirmed that it successfully runs `.mf6minsim` in parallel on a Windows machine without Visual Studio, oneAPI or PETSc preinstalled.

**Comment by wpbonelli** [comment]
also updated the readme badge to correspond to https://github.com/MODFLOW-USGS/modflow6-nightly-build/pull/52

**Comment by mjr-deltares** [comment]
I will test this on a clean Windows 10 image, should be done today

**Comment by mjr-deltares** [comment]
C:\Users\user\Downloads\modflow6-develop\modflow6-develop\.mf6minsim>..\..\..\mf6.5.0.dev2_win64par\bin\mpiexec.exe -np 2 ..\..\..\mf6.5.0.dev2_win64par\bin\mf6.exe -p


                               MODFLOW 6 EXTENDED
                U.S. GEOLOGICAL SURVEY MODULAR HYDROLOGIC MODEL
                  VERSION 6.5.0.dev2 (preliminary) 03/20/2024
                               ***DEVELOP MODE***

   MODFLOW 6 compiled Mar 20 2024 15:48:04 with Intel(R) Fortran Intel(R) 64
  Compiler Classic for applications running on Intel(R) 64, Version 2021.11.1
                             Build 20231117_000000

This software is preliminary or provisional and is subject to
revision. It is being provided to meet the need for timely best
science. The software has not received final approval by the U.S.
Geological Survey (USGS). No warranty, expressed or implied, is made
by the USGS or the U.S. Government as to the functionality of the
software and related material nor shall the fact of release
constitute any such warranty. The software is provided on the
condition that neither the USGS nor the U.S. Government shall be held
liable for any damages resulting from the authorized or unauthorized
use of the software.


(MODFLOW runs in PARALLEL mode)

 Run start date and time (yyyy/mm/dd hh:mm:ss): 2024/03/21 15:02:18

 Writing simulation list file: mfsim.p1.lst
 Using Simulation name file: mfsim.nam

                               MODFLOW 6 EXTENDED
                U.S. GEOLOGICAL SURVEY MODULAR HYDROLOGIC MODEL
                  VERSION 6.5.0.dev2 (preliminary) 03/20/2024
                               ***DEVELOP MODE***

   MODFLOW 6 compiled Mar 20 2024 15:48:04 with Intel(R) Fortran Intel(R) 64
  Compiler Classic for applications running on Intel(R) 64, Version 2021.11.1
                             Build 20231117_000000

This software is preliminary or provisional and is subject to
revision. It is being provided to meet the need for timely best
science. The software has not received final approval by the U.S.
Geological Survey (USGS). No warranty, expressed or implied, is made
by the USGS or the U.S. Government as to the functionality of the
software and related material nor shall the fact of release
constitute any such warranty. The software is provided on the
condition that neither the USGS nor the U.S. Government shall be held
liable for any damages resulting from the authorized or unauthorized
use of the software.


(MODFLOW runs in PARALLEL mode)

 Run start date and time (yyyy/mm/dd hh:mm:ss): 2024/03/21 15:02:18

 Writing simulation list file: mfsim.p0.lst
 Using Simulation name file: mfsim.nam

    Solving:  Stress period:     1    Time step:     1
    Solving:  Stress period:     1    Time step:     1
INTEL MKL ERROR: The specified module could not be found. mkl_mc3.2.dll.
Intel MKL FATAL ERROR: Cannot load mkl_mc3.2.dll or mkl_def.2.dll.
INTEL MKL ERROR: The specified module could not be found. mkl_mc3.2.dll.
Intel MKL FATAL ERROR: Cannot load mkl_mc3.2.dll or mkl_def.2.dll.

C:\Users\user\Downloads\modflow6-develop\modflow6-develop\.mf6minsim>

**Comment by mjr-deltares** [comment]
and copying in mkl_mc3.2.dll solves the issue!

**Review by mjr-deltares — APPROVED** [review]
I think this is great. We just need to copy in one more dll it seems (see comments).

**Comment by wpbonelli** [comment]
Thanks @mjr-deltares I will add that last dll, verify, and then merge shortly!

**Comment by wpbonelli** [comment]
I tested on an EC2 box and found it was also necessary to include `mkl_def.2.dll` and `mkl_avx2.2.dll`

**Pull request merged**
