### PR TITLE
docs(styleguide) Add formatting and explanations to the Style guide 

### PR DESCRIPTION
**Pull request by Manangka**
In this PR the styleguide has been extended

- The rules have grouped in different sections to which can be linked
- Examples have been added to most of the rules to clarify the intent

Checklist of items for pull request

- [ ] Closed issue #xxxx
- [ ] Referenced issue or pull request #xxxx
- [ ] Added new test or modified an existing test
- [ ] Ran `black` on new and modified autotests
- [ ] Formatted new and modified Fortran source files with `fprettify`
- [ ] Added doxygen comments to new and modified procedures
- [ ] Updated meson files, makefiles, and Visual Studio project files for new source files
- [ ] Updated [definition files](/MODFLOW-USGS/modflow6/tree/develop/doc/mf6io/mf6ivar)
- [ ] Updated [develop.tex](/MODFLOW-USGS/modflow6/doc/ReleaseNotes/develop.tex) with a plain-language description of the bug fix, change, feature; required for changes that may affect users
- [ ] Updated [input and output guide](/MODFLOW-USGS/modflow6/doc/mf6io)
- [ ] Removed checklist items not relevant to this pull request

For additional information see [instructions for contributing](/MODFLOW-USGS/modflow6/.github/CONTRIBUTING.md) and [instructions for developing](/MODFLOW-USGS/modflow6/.github/DEVELOPER.md).

### CODE REVIEW

**Comment by Manangka** [comment]
@wpbonelli This is still a work in progress but tagging you here to keep you in the loop

**Review by wpbonelli — APPROVED** [review]
@Manangka LGTM so far.

**Comment by Manangka** [comment]
@wpbonelli I'm done with the bulk of the work. There are a few rules I had trouble explaining.  Those were:
- Avoid `implicit none` in procedures except where necessary (e.g. interface bodies).
- Don't use implicit dummy arguments or local variables.

I also found the `Include blank lines between:` rules a bit vague

Could you have a look at those rules?

**Comment by Manangka** [comment]
Alright. I removed the superfluous implicit rules.

We might also need to think about the layout. For isntance it could be useful if the rules have a rule number or a rule id to which we can refer.
I'm thinking about something like:

> M.1 Use implicit none in all modules
> M.2 Make modules private by default. Mark public types and procedures explicitly
> ...
> P.1 Don’t end procedures with a return statement; use return only to return early

**Comment by langevin-usgs** [comment]
> I like that idea. Should we merge to get an updated render on RTD for feedback, and keep developing in separate PRs?

Would be great to get this merged so others can easily see on RTD.

**Comment by mjr-deltares** [comment]
Nice job guys, lovin' it!

**Pull request merged**
