### PR TITLE
fix(sfr): update budget and table output for inactive reaches

### PR DESCRIPTION
**Pull request by jdhughes-usgs**
Add evaluation of DHNOFLO value in tables

### CODE REVIEW

**Comment by jdhughes-usgs** [comment]
Tables with inactive reaches

```
SFR_0 PACKAGE - SUMMARY OF FLOWS FOR EACH CONTROL VOLUME   PERIOD      2   STEP        1
 ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
                                                                                                                                                                     PERCENT   
   NUMBER   CELLID                  INFLOW      OUTFLOW        GWF        RAINFALL   EVAPORATION     RUNOFF     EXT INFLOW  EXT OUTFLOW    STORAGE      IN - OUT    DIFFERENCE 
 ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
     1      (1,1,1)               0.0000       0.0000       0.81454      1.0000      -1.0000       1.0000       1.0000      -2.8145       0.0000       0.0000       0.0000     
     2      (1,1,1)               0.0000       0.0000       0.0000       0.0000       0.0000       0.0000       0.0000       0.0000       0.0000       0.0000       0.0000     
 ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------



 SFR PACKAGE (SFR_0) STAGES FOR EACH CONTROL VOLUME   PERIOD      2   STEP        1
 -------------------------------------------------------------------------------------------------------------
                                                                                      STREAMBED    STREAMBED  
   NUMBER   CELLID                  STAGE        DEPTH        WIDTH       GWF HEAD   CONDUCTANCE    GRADIENT  
 -------------------------------------------------------------------------------------------------------------
     1      (1,1,1)               0.18546      0.18546      1.0000       1.0000       1.0000      -0.81454    
     2      (1,1,1)                INACTIVE     INACTIVE     INACTIVE    1.0000        INACTIVE     INACTIVE  
 -------------------------------------------------------------------------------------------------------------
```

**Comment by jdhughes-usgs** [comment]
Updates on the tables

**Stress period 1 with dry reach 1**

```
SFR-1 PACKAGE - SUMMARY OF FLOWS FOR EACH CONTROL VOLUME   PERIOD      1   STEP        1
 --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
                                                                                                                                                                                               PERCENT   
   NUMBER   CELLID                  INFLOW      OUTFLOW        GWF        RAINFALL   EVAPORATION     RUNOFF     EXT INFLOW  EXT OUTFLOW    STORAGE      FROM MVR      TO MVR      IN - OUT    DIFFERENCE 
 --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
     1      NONE                  0.0000       0.0000       0.0000       0.0000       0.0000       0.0000       0.0000       0.0000       0.0000       0.0000       0.0000       0.0000       0.0000     
     2      (1,1,1)               0.0000       0.0000       0.92094      0.0000       0.0000       0.0000       0.0000      -0.92094      0.0000       0.0000       0.0000       0.0000       0.0000     
     3      (1,1,1)               0.0000      -2.8145       0.81454      1.0000      -1.0000       1.0000       1.0000       0.0000       0.0000       0.0000       0.0000       0.0000       0.0000     
     4      (1,1,1)               2.8145       0.0000       0.72502      1.0000      -1.0000       1.0000       0.0000      -4.5396       0.0000       0.0000       0.0000       0.0000       0.0000     
 --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------



 SFR PACKAGE (SFR-1) STAGES FOR EACH CONTROL VOLUME   PERIOD      1   STEP        1
 -------------------------------------------------------------------------------------------------------------
                                                                                      STREAMBED    STREAMBED  
   NUMBER   CELLID                  STAGE        DEPTH        WIDTH       GWF HEAD   CONDUCTANCE    GRADIENT  
 -------------------------------------------------------------------------------------------------------------
     1      NONE                     DRY       0.0000       0.0000           --           --           --     
     2      (1,1,1)               7.90536E-02  7.90536E-02  1.0000       1.0000       1.0000      -0.92094    
     3      (1,1,1)               0.18546      0.18546      1.0000       1.0000       1.0000      -0.81454    
     4      (1,1,1)               0.27498      0.27498      1.0000       1.0000       1.0000      -0.72502    
 -------------------------------------------------------------------------------------------------------------
```

**Stress Period 2 with inactive reach 4 and mover from reach 3 to reach 1**
```
SFR-1 PACKAGE - SUMMARY OF FLOWS FOR EACH CONTROL VOLUME   PERIOD      2   STEP        1
 --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
                                                                                                                                                                                               PERCENT   
   NUMBER   CELLID                  INFLOW      OUTFLOW        GWF        RAINFALL   EVAPORATION     RUNOFF     EXT INFLOW  EXT OUTFLOW    STORAGE      FROM MVR      TO MVR      IN - OUT    DIFFERENCE 
 --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
     1      NONE                  0.0000      -2.8145       0.0000       0.0000       0.0000       0.0000       0.0000       0.0000       0.0000       2.8145       0.0000       0.0000       0.0000     
     2      (1,1,1)               2.8145       0.0000       0.74757      0.0000       0.0000       0.0000       0.0000      -3.5621       0.0000       0.0000       0.0000       0.0000       0.0000     
     3      (1,1,1)               0.0000       0.0000       0.81454      1.0000      -1.0000       1.0000       1.0000      -1.68460E-07  0.0000       0.0000      -2.8145       0.0000       0.0000     
     4      (1,1,1)               0.0000       0.0000       0.0000       0.0000       0.0000       0.0000       0.0000       0.0000       0.0000       0.0000       0.0000       0.0000       0.0000     
 --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

SFR PACKAGE (SFR-1) STAGES FOR EACH CONTROL VOLUME   PERIOD      2   STEP        1
 -------------------------------------------------------------------------------------------------------------
                                                                                      STREAMBED    STREAMBED  
   NUMBER   CELLID                  STAGE        DEPTH        WIDTH       GWF HEAD   CONDUCTANCE    GRADIENT  
 -------------------------------------------------------------------------------------------------------------
     1      NONE                  0.23423      0.23423      1.0000           --           --           --     
     2      (1,1,1)               0.25243      0.25243      1.0000       1.0000       1.0000      -0.74757    
     3      (1,1,1)               0.18546      0.18546      1.0000       1.0000       1.0000      -0.81454    
     4      (1,1,1)                INACTIVE     INACTIVE     INACTIVE    1.0000        INACTIVE     INACTIVE  
 -------------------------------------------------------------------------------------------------------------
```

**Comment by jdhughes-usgs** [comment]
Final updates on the tables

**Stress period 1 with dry reach 3**
```
SFR-1 PACKAGE - SUMMARY OF FLOWS FOR EACH CONTROL VOLUME   PERIOD      1   STEP        1
 --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
                                                                                                                                                                                               PERCENT   
   NUMBER   CELLID                  INFLOW      OUTFLOW        GWF        RAINFALL   EVAPORATION     RUNOFF     EXT INFLOW  EXT OUTFLOW    STORAGE      FROM MVR      TO MVR      IN - OUT    DIFFERENCE 
 --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
     1      (1,1,1)               0.0000      -2.8145       0.81454      1.0000      -1.0000       1.0000       1.0000       0.0000       0.0000       0.0000       0.0000       0.0000       0.0000     
     2      (1,1,1)               2.8145       0.0000       0.72502      1.0000      -1.0000       1.0000       0.0000      -4.5396       0.0000       0.0000       0.0000       0.0000       0.0000     
     3      NONE                  0.0000       0.0000       0.0000       0.0000       0.0000       0.0000       0.0000       0.0000       0.0000       0.0000       0.0000       0.0000       0.0000     
     4      (1,1,1)               0.0000       0.0000       0.92094      0.0000       0.0000       0.0000       0.0000      -0.92094      0.0000       0.0000       0.0000       0.0000       0.0000     
 --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------



 SFR PACKAGE (SFR-1) STAGES FOR EACH CONTROL VOLUME   PERIOD      1   STEP        1
 -------------------------------------------------------------------------------------------------------------
                                                                                      STREAMBED    STREAMBED  
   NUMBER   CELLID                  STAGE        DEPTH        WIDTH       GWF HEAD   CONDUCTANCE    GRADIENT  
 -------------------------------------------------------------------------------------------------------------
     1      (1,1,1)               0.18546      0.18546      1.0000       1.0000       1.0000      -0.81454    
     2      (1,1,1)               0.27498      0.27498      1.0000       1.0000       1.0000      -0.72502    
     3      NONE                     DRY       0.0000       0.0000           --           --           --     
     4      (1,1,1)               7.90536E-02  7.90536E-02  1.0000       1.0000       1.0000      -0.92094    
 -------------------------------------------------------------------------------------------------------------
```

**Stress Period 2 with inactive reach 2 and mover from reach 1 to reach 4**
```
SFR-1 PACKAGE - SUMMARY OF FLOWS FOR EACH CONTROL VOLUME   PERIOD      2   STEP        1
 --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
                                                                                                                                                                                               PERCENT   
   NUMBER   CELLID                  INFLOW      OUTFLOW        GWF        RAINFALL   EVAPORATION     RUNOFF     EXT INFLOW  EXT OUTFLOW    STORAGE      FROM MVR      TO MVR      IN - OUT    DIFFERENCE 
 --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
     1      (1,1,1)               0.0000       0.0000       0.81454      1.0000      -1.0000       1.0000       1.0000      -1.68460E-07  0.0000       0.0000      -2.8145       0.0000       0.0000     
     2      (1,1,1)               0.0000       0.0000       0.0000       0.0000       0.0000       0.0000       0.0000       0.0000       0.0000       0.0000       0.0000       0.0000       0.0000     
     3      NONE                  0.0000       0.0000       0.0000       0.0000       0.0000       0.0000       0.0000       0.0000       0.0000       0.0000       0.0000       0.0000       0.0000     
     4      (1,1,1)               0.0000       0.0000       0.74757      0.0000       0.0000       0.0000       0.0000      -3.5621       0.0000       2.8145       0.0000       0.0000       0.0000     
 --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


SFR PACKAGE (SFR-1) STAGES FOR EACH CONTROL VOLUME   PERIOD      2   STEP        1
 -------------------------------------------------------------------------------------------------------------
                                                                                      STREAMBED    STREAMBED  
   NUMBER   CELLID                  STAGE        DEPTH        WIDTH       GWF HEAD   CONDUCTANCE    GRADIENT  
 -------------------------------------------------------------------------------------------------------------
     1      (1,1,1)               0.18546      0.18546      1.0000       1.0000       1.0000      -0.81454    
     2      (1,1,1)                INACTIVE     INACTIVE     INACTIVE    1.0000        INACTIVE     INACTIVE  
     3      NONE                     DRY       0.0000       0.0000           --           --           --     
     4      (1,1,1)               0.25243      0.25243      1.0000       1.0000       1.0000      -0.74757    
 -------------------------------------------------------------------------------------------------------------
```

**Review by langevin-usgs — APPROVED** [review]
Looks good

**Pull request merged**
