### PR TITLE
chore(gwf-sfr.f90): stylistic consistency

### PR DESCRIPTION
**Pull request by emorway-usgs**
- minor stuff for consistent presentation
- fprettify

### CODE REVIEW

**Comment by emorway-usgs** [comment]
> @jdhughes-usgs, is this going to conflict with your SFR refactoring?

There will definitely be conflicts.  I can wait until #1761 goes in and get this PR up-to-date.  

Before initiating this PR, I checked to see if there were any open PRs with SFR modifications.  Not seeing any, I submitted this one, but it looks like it was only shortly before #1761.

**Comment by jdhughes-usgs** [comment]
> > @jdhughes-usgs, is this going to conflict with your SFR refactoring?
> 
> There will definitely be conflicts. I can wait until #1761 goes in and get this PR up-to-date.
> 
> Before initiating this PR, I checked to see if there were any open PRs with SFR modifications. Not seeing any, I submitted this one, but it looks like it was only shortly before #1761.

@langevin-usgs @emorway-usgs Yes this will conflict with my refactoring.

**Comment by jdhughes-usgs** [comment]
@langevin-usgs @emorway-usgs @wpbonelli I also don't think we should be capitalizing the first letter of a comment if it is not a sentence. We need to get finalize the Fortran style for mf6 and get a python tool up and running.

**Comment by langevin-usgs** [comment]
I'm going to close this for now.  We might need to formalize commenting style before making these changes

**Pull request closed without merging**
