### PR TITLE
ci(netcdf): windows extended build and tests

### PR DESCRIPTION
**Pull request by mjreno**
Add CI testing for windows based netcdf and extended builds:
    -- NetCDF-C (4.9.2) pre-compiled libraries used to build fortran libraries
    -- NetCDF-Fortran libraries built from source (4.6.1) with ifort and cmake
    -- Modflow 6 builds and tests added for netcdf only and parallel + netcdf (extended)
    -- release workflow update replaces windows parallel with extended build

Checklist of items for pull request
- [X] Replaced section above with description of pull request
- [X] Added new test or modified an existing test
- [X] Ran `ruff` on new and modified python scripts in .doc, autotests, doc, distribution, pymake, and utils subdirectories.
- [X] Removed checklist items not relevant to this pull request

For additional information see [instructions for contributing](/MODFLOW-USGS/modflow6/.github/CONTRIBUTING.md) and [instructions for developing](/MODFLOW-USGS/modflow6/.github/DEVELOPER.md).

### CODE REVIEW

**Review by langevin-usgs — APPROVED** [review]
@mjreno, I've looked through this and think it looks great.  It will be nice to see how stable it is over time.  I think this extended build is a key part for moving all this forward, so many thinks for getting this up and running.

**Comment by mjr-deltares** [comment]
Nice Job @mjreno !  I am working on fixing the builds on macos in PR #2044 and will ping you when we are good to go

**Review by wpbonelli — COMMENTED** [review]
It looks like the tests run a separate parallel, netcdf, and extended build. Should we release these as separate distributions, or is the extended build going to replace the parallel build? In either case flopy's get-modflow script will need a change here https://github.com/modflowpy/flopy/blob/9349a07e910095ca501c32106fbb50087c679668/flopy/utils/get_modflow.py#L38 and below on line 71 to handle the new cases.

**Comment by mjr-deltares** [comment]
> It looks like the tests run a separate parallel, netcdf, and extended build. Should we release these as separate distributions, or is the extended build going to replace the parallel build? In either case flopy's get-modflow script will need a change here https://github.com/modflowpy/flopy/blob/9349a07e910095ca501c32106fbb50087c679668/flopy/utils/get_modflow.py#L38 and below on line 71 to handle the new cases.

I think that extended replaces parallel.  @jdhughes-usgs agree?

**Comment by jdhughes-usgs** [comment]
> > It looks like the tests run a separate parallel, netcdf, and extended build. Should we release these as separate distributions, or is the extended build going to replace the parallel build? In either case flopy's get-modflow script will need a change here https://github.com/modflowpy/flopy/blob/9349a07e910095ca501c32106fbb50087c679668/flopy/utils/get_modflow.py#L38 and below on line 71 to handle the new cases.
> 
> I think that extended replaces parallel. @jdhughes-usgs agree?

I agree. We probably also need to look for either `ext` or `par` so older versions can be downloaded.

**Pull request merged**
