### PR TITLE
test: accommodate single-precision comparison programs

### PR DESCRIPTION
**Pull request by wpbonelli**
Double-precision versions of mf2005, mfnwt, mfusg and mflgr have been removed from [version 15 of the executables distribution](https://github.com/MODFLOW-USGS/executables/releases/tag/15.0). I think some autotests either need modification to work with the single-precision programs, or the test framework needs to build double-precision versions with pymake before testing.

Anticipating the former option this PR
* drops double-precision programs from test targets dict
* updates test_gwt_mt3dms_p01 to use single prec mf2005
* could relax comparisons in failing tests, if that is an appropriate solution

...but the above can be walked back if building and testing with double-precision versions is preferred.

Tests are expected to fail here in the meantime.

### CODE REVIEW

**Comment by jdhughes-usgs** [comment]
@langevin-usgs shouldn't all of the GWT test problems that compare to live numerical results not be converted to compare to previous mf6 versions since GWT has been in mf6 for years?

**Comment by langevin-usgs** [comment]
@jdhughes-usgs, if you are asking if this test could be converted to a regression test (with a comparison to results from the last mf6 release) I think the answer is yes.

**Comment by jdhughes-usgs** [comment]
@langevin-usgs Not really a question but seems pointless to compare to older versions of MODFLOW once a feature has been in for more that one release. 

I could make a new pymake release that restores building double precision versions of certain exes if that is what is wanted.

**Comment by langevin-usgs** [comment]
We can get this test to achieve its purpose without having to restore the double precision exes.  I can work on that.

**Comment by wpbonelli** [comment]
the failing tests, to my count, are

```
FAILED test_gwf_sto01.py::test_mf6model[0-gwf_sto01] - ValueError: times in two head files are not equal (1.0,6.013470016999068e-154)
FAILED test_gwf_npf01_75x75.py::test_mf6model[0-npf01a_75x75] - ValueError: times in two head files are not equal (1.0,6.013470016999068e-154)
FAILED test_gwf_npf01_75x75.py::test_mf6model[1-npf01b_75x75] - ValueError: times in two head files are not equal (1.0,6.013470016999068e-154)
FAILED test_gwf_csub_zdisp01.py::test_mf6model[0-csub_zdisp01] - IndexError: index 0 is out of bounds for axis 0 with size 0
FAILED test_examples.py::test_scenario[ex-gwt-saltlake] - AssertionError: budget comparison failed
FAILED test_examples.py::test_scenario[ex-gwt-synthetic-valley] - AssertionError: Comparison model failed
FAILED test_examples.py::test_scenario[ex-gwt-rotate] - AssertionError: budget comparison failed
FAILED test_largetestmodels.py::test_model[/Users/wbonelli/dev/modflow6-largetestmodels/test1005_secp/mfsim.nam] - AssertionError: budget comparison failed
```

**Pull request closed without merging**
