### PR TITLE
Fix backspace

### PR DESCRIPTION
**Pull request by rleander**

### CODE REVIEW

**Comment by langevin-usgs** [comment]
Hi @rleander, thanks for submitting this PR.  We will all be quite happy to get compiling again with the latest OneAPI.  Can you take a look at the few minor checks that are failing.  You will need to run fprettify to format the source code (hopefully the error message will give you a hint on how to do that), and it looks like a few more changes will be required to the utility programs so they can also use the revised utility.  Thank you for your help with this.

**Comment by mjr-deltares** [comment]
Hi @langevin-usgs , @rleander and myself were also discussing if we could somehow contain these changes to the file parsing part and not have them go up and affect RCH or EVT etc. So maybe that will be a minor tweak as well.

**Comment by mjr-deltares** [comment]
Hi @rleander , we noticed you have another PR up on this. Does that replace the current? (and can it then be closed)

**Comment by mjr-deltares** [comment]
discussed with @rleander to close this (for now)

**Pull request closed without merging**
